# Generated by Django 4.2.5 on 2023-09-30 08:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mgmt.wireguard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('start_ip', models.GenericIPAddressField(verbose_name='Start IP')),
                ('size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)], verbose_name='Size')),
                ('gateway_ip', models.GenericIPAddressField(verbose_name='Gateway IP(Local)')),
                ('global_ip', models.GenericIPAddressField(verbose_name='Global IP')),
                ('global_port', models.IntegerField(default=51820, verbose_name='Global Port')),
                ('mgmt_ip', models.GenericIPAddressField(verbose_name='Management IP')),
                ('mgmt_port', models.IntegerField(default=8080, verbose_name='Management Port')),
                ('private_key', models.CharField(max_length=250, verbose_name='秘密鍵')),
                ('public_key', models.CharField(max_length=250, verbose_name='公開鍵')),
            ],
            options={
                'verbose_name': 'Wireguardサーバ',
                'verbose_name_plural': 'Wireguardサーバ',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('count', models.IntegerField(default=mgmt.wireguard.models.init_gen_count, verbose_name='count')),
                ('public_key', models.CharField(max_length=250, verbose_name='公開鍵')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wireguardサービス',
                'verbose_name_plural': 'Wireguardサービス',
            },
        ),
    ]
