# Generated by Django 4.2.5 on 2023-10-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.CharField(default='', max_length=250, verbose_name='コメント'),
        ),
    ]
