# Generated by Django 4.2.5 on 2023-10-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0002_client_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='comment',
            field=models.CharField(default='', max_length=250, verbose_name='コメント'),
        ),
    ]
