# Generated by Django 4.2.5 on 2023-10-01 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mgmt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('access_type', models.CharField(choices=[('ssh', 'ssh'), ('telnet', 'telnet')], default='ssh', max_length=100, verbose_name='access_type')),
                ('username', models.CharField(default='', max_length=250, verbose_name='ユーザ名')),
                ('password', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='パスワード')),
                ('comment', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='コメント')),
            ],
            options={
                'verbose_name': 'Auth',
                'verbose_name_plural': 'Auth',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.CharField(max_length=100, verbose_name='カテゴリ1')),
                ('category2', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='カテゴリ2')),
                ('category3', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='カテゴリ3')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('commands', mgmt.models.MediumTextField(default='', verbose_name='commands')),
                ('ignore_lines', mgmt.models.MediumTextField(blank=True, default='', null=True, verbose_name='ignore_lines')),
                ('config_start', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='config_start')),
                ('config_end', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='config_end')),
                ('comment', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='コメント')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Template',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('hostname', models.CharField(default='', max_length=250, verbose_name='hostname')),
                ('address', models.GenericIPAddressField(verbose_name='Address')),
                ('comment', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='コメント')),
                ('auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='remote.auth')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote.template')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Device',
            },
        ),
    ]
